services:
  - type: web
    name: feather-press
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_SSL
        value: true
      - key: FRONTEND_URL
        value: https://feather-press-1.netlify.app
    disk:
      name: uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1